// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package test.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Test module
	public static java.lang.String createCredentials(IContext context, test.proxies.Credential _newCredentialsObject)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NewCredentialsObject", _newCredentialsObject == null ? null : _newCredentialsObject.getMendixObject());
		return (java.lang.String) Core.microflowCall("Test.CreateCredentials").withParams(params).execute(context);
	}
	public static void iVK_CheckUserInput(IContext context, test.proxies.ValidityCheck _validityCheck)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ValidityCheck", _validityCheck == null ? null : _validityCheck.getMendixObject());
		Core.microflowCall("Test.IVK_CheckUserInput").withParams(params).execute(context);
	}
	public static boolean iVK_IsCodeValid(IContext context, java.lang.String _inputValueFromUser, java.lang.String _secretKey)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("InputValueFromUser", _inputValueFromUser);
		params.put("SecretKey", _secretKey);
		return (java.lang.Boolean) Core.microflowCall("Test.IVK_IsCodeValid").withParams(params).execute(context);
	}
	public static void iVK_NewUser(IContext context, test.proxies.Credential _credential)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Credential", _credential == null ? null : _credential.getMendixObject());
		Core.microflowCall("Test.IVK_NewUser").withParams(params).execute(context);
	}
	public static void iVK_ShowCheckCode(IContext context, test.proxies.Credential _credential)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Credential", _credential == null ? null : _credential.getMendixObject());
		Core.microflowCall("Test.IVK_ShowCheckCode").withParams(params).execute(context);
	}
}