// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package test.proxies;

public class ValidityCheck
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject validityCheckMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Test.ValidityCheck";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SecretKey("SecretKey"),
		Validation_Code("Validation_Code");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ValidityCheck(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Test.ValidityCheck"));
	}

	protected ValidityCheck(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject validityCheckMendixObject)
	{
		if (validityCheckMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Test.ValidityCheck", validityCheckMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Test.ValidityCheck");

		this.validityCheckMendixObject = validityCheckMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ValidityCheck.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static test.proxies.ValidityCheck initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return test.proxies.ValidityCheck.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static test.proxies.ValidityCheck initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new test.proxies.ValidityCheck(context, mendixObject);
	}

	public static test.proxies.ValidityCheck load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return test.proxies.ValidityCheck.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SecretKey
	 */
	public final java.lang.String getSecretKey()
	{
		return getSecretKey(getContext());
	}

	/**
	 * @param context
	 * @return value of SecretKey
	 */
	public final java.lang.String getSecretKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SecretKey.toString());
	}

	/**
	 * Set value of SecretKey
	 * @param secretkey
	 */
	public final void setSecretKey(java.lang.String secretkey)
	{
		setSecretKey(getContext(), secretkey);
	}

	/**
	 * Set value of SecretKey
	 * @param context
	 * @param secretkey
	 */
	public final void setSecretKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secretkey)
	{
		getMendixObject().setValue(context, MemberNames.SecretKey.toString(), secretkey);
	}

	/**
	 * @return value of Validation_Code
	 */
	public final java.lang.String getValidation_Code()
	{
		return getValidation_Code(getContext());
	}

	/**
	 * @param context
	 * @return value of Validation_Code
	 */
	public final java.lang.String getValidation_Code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Validation_Code.toString());
	}

	/**
	 * Set value of Validation_Code
	 * @param validation_code
	 */
	public final void setValidation_Code(java.lang.String validation_code)
	{
		setValidation_Code(getContext(), validation_code);
	}

	/**
	 * Set value of Validation_Code
	 * @param context
	 * @param validation_code
	 */
	public final void setValidation_Code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String validation_code)
	{
		getMendixObject().setValue(context, MemberNames.Validation_Code.toString(), validation_code);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return validityCheckMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final test.proxies.ValidityCheck that = (test.proxies.ValidityCheck) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Test.ValidityCheck";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
